"""
Django settings for finance_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")

APPEND_SLASH = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'finance_app',
    'rest_framework',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "finance_app.middleware.JWTAuthMiddleware",
]

ROOT_URLCONF = 'finance_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'finance_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# Load .env file
# load_dotenv()

# DEBUG = os.getenv('DEBUG', 'False') == 'True'
# SECRET_KEY = os.getenv('SECRET_KEY')

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME_FOR_USER'),
#         'USER': os.getenv('DB_USER_FOR_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD_FOR_USER'),
#         'HOST': os.getenv('DB_HOST_FOR_USER', 'localhost'),
#         'PORT': os.getenv('DB_PORT_FOR_USER', '5432'),
#     }
# }

# import os
# from dotenv import load_dotenv

# load_dotenv()

# DEBUG = os.getenv('DEBUG', 'False') == 'True'
# SECRET_KEY = os.getenv('SECRET_KEY')

# DATABASES = {
#     'default': {   # finance_db (django auth)
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME_FOR_USER'),
#         'USER': os.getenv('DB_USER_FOR_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD_FOR_USER'),
#         'HOST': os.getenv('DB_HOST_FOR_USER', 'db'),
#         'PORT': os.getenv('DB_PORT_FOR_USER', '5432'),
#     },
#     'finance_ai': {   # finance_ai_db (for ai_data app)
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME_FOR_AI'),
#         'USER': os.getenv('DB_USER_FOR_AI'),
#         'PASSWORD': os.getenv('DB_PASSWORD_FOR_AI'),
#         'HOST': os.getenv('DB_HOST_FOR_AI', 'db'),
#         'PORT': os.getenv('DB_PORT_FOR_AI', '5432'),
#     }
# }

# DATABASE_ROUTERS = ['finance_project.db_router.DatabaseRouter']


import os
from dotenv import load_dotenv

load_dotenv()

DEBUG = os.getenv('DEBUG', 'False') == 'True'
SECRET_KEY = os.getenv('SECRET_KEY')

DATABASES = {
    'default': {  # finance_db
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME_FOR_USER'),
        'USER': os.getenv('DB_USER_FOR_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD_FOR_USER'),
        'HOST': os.getenv('DB_HOST_FOR_USER', 'db'),
        'PORT': os.getenv('DB_PORT_FOR_USER', '5432'),
    },
    'finance_ai': {  # finance_ai_db
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME_FOR_AI'),
        'USER': os.getenv('DB_USER_FOR_AI'),
        'PASSWORD': os.getenv('DB_PASSWORD_FOR_AI'),
        'HOST': os.getenv('DB_HOST_FOR_AI', 'db'),
        'PORT': os.getenv('DB_PORT_FOR_AI', '5432'),
    }
}

DATABASE_ROUTERS = ['finance_project.db_router.DatabaseRouter']



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

import os
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "finance_app" / "static"]
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# FASTAPI_URL = "http://127.0.0.1:8001"

import os

# ... tumhara existing settings ...
FASTAPI_URL = os.getenv("FASTAPI_URL", "http://fastapi:8001")



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),   # Access token 15 min
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=5),     # Refresh token 5 hours
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
