# Generated by Django 5.2.5 on 2025-08-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqueryhistory',
            name='chart_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
