# Generated by Django 5.2.5 on 2025-09-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQueryHistory',
        ),
    ]
